### ISSUE TITLE
user not found

### ISSUE THREAD

**Issue by spider1998** [togettoyou/blockchain-real-estate#2]
您好，按流程运行后，web界面正常，首页访问会报：failed to create channel context: failed to get client context to create channel client: user not found，查询用户列表失败，但是Admin用户在- CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/users/Admin@org1.blockchainrealestate.com/msp  中已加入，请问是少了什么配置吗？期待您的回复，谢谢

**Comment by togettoyou** [comment]
您好，源码我已更新，修复了sdk_test.go的使用。请作如下检查

1. 请确保你的项目目录为`$GOPATH/src/github.com/togettoyou/blockchain-real-estate`
2. 项目由于未使用mod管理，请先将go mod环境设置为auto： `go env -w GO111MODULE=auto`
3. 首先测试chaincode是否正常调用，运行`chaincode/blockchain-real-estate/chaincode_test.go`测试用例
![image](https://user-images.githubusercontent.com/55381228/85498013-8200a100-b611-11ea-938f-9ac1d3ad5b89.png)

4. 在deploy目录下运行`./start.sh`,请观察有无报错提示。运行成功后在终端执行`docker exec cli peer chaincode invoke -C assetschannel -n blockchain-real-estate -c '{"Args":["queryAccountList"]}'` 等cli命令，Args可以替换为Invoke中的funcName，先验证链码是否正确安装及区块链网络能否正常工作。建议你`./start.sh`之前可以先运行`./stop.sh`清理一下环境。
![image](https://user-images.githubusercontent.com/55381228/85497727-0141a500-b611-11ea-8d10-deacb8bd627e.png)

5. 如果以上都成功，说明区块链网络是没有问题的。接下来同样请先执行`application/sdk_test.go`单元测试，看是否可以成功使用sdk调用链码(此步骤前提你区块链网络即以上步骤已成功启动)
![image](https://user-images.githubusercontent.com/55381228/85497628-d7887e00-b610-11ea-9749-0006ad0df814.png)

6. 运行application，`go run main.go` 

我猜测你的是第4步网络启动过程出错。请排查。

我的本机测试环境：
![image](https://user-images.githubusercontent.com/55381228/85497883-4960c780-b611-11ea-93b0-4a2ec69b8142.png)

**Comment by togettoyou** [comment]
fabric的环境安装请参考：[https://www.yuque.com/togettoyou/blog/his57f](https://www.yuque.com/togettoyou/blog/his57f)

**Comment by spider1998** [comment]
感谢您的回复！根据你的提示我最终解决了问题，我用的是go mod管理项目依赖，导致项目路径配置出现了问题，现在已经解决。再次感谢你的回复，我已经将你项目的部分应用到我的新项目中并成功运行，感谢！
