### ISSUE TITLE
第二部启动时，镜像拉取失败

### ISSUE THREAD

**Issue by Admaing** [togettoyou/blockchain-real-estate#20]
![image](https://user-images.githubusercontent.com/38456638/141395288-74e251cb-987c-4fcb-9aaf-4d5b93c80336.png)

**Comment by togettoyou** [comment]
更换镜像源
https://github.com/togettoyou/blockchain-real-estate/blob/master/Install.md

**Comment by Admaing** [comment]
更换了已经，仍旧报同样的错误

**Comment by Admaing** [comment]
更改镜像源之后解决了问题，感谢！
