### ISSUE TITLE
请您指教——浏览器访问 http://localhost:8000/web 读不出数据

### ISSUE THREAD

**Issue by skyejy** [togettoyou/blockchain-real-estate#5]
您好 ，我们按照您的步骤运行到了浏览器访问 http://localhost:8000/web这一步，顺利打开了网页，但“无数据”，报错“请求失败，timeout of 5000ms exceeded”
还望您指教，非常感谢！

**Comment by togettoyou** [comment]
1、区块链网络和后端也是部署在本地吗，如果不是，则env.production文件里面的URL是否正确，参考https://github.com/togettoyou/blockchain-real-estate/issues/4
2、application是否启动，是否可以访问 http://localhost:8000/api/v1/hello
      接口列表参考https://github.com/togettoyou/blockchain-real-estate/blob/master/application/routers/router.go
3、浏览器访问 http://localhost:8000/web  打开F12控制台，查看报错详情

**Comment by togettoyou** [comment]
执行`docker exec cli peer chaincode invoke -C assetschannel -n blockchain-real-estate -c '{"Args":["queryAccountList"]}'`
看是否有输出信息，确保区块链网络已成功启动！

**Comment by skyejy** [comment]
![image](https://user-images.githubusercontent.com/26304541/102352840-3daff580-3fe3-11eb-9c6a-3fcc67921972.png)
您好，感谢您解答上一个问题。 我们又重新安装部署了一遍，这次先进行的是测试chaincode是否正常调用，遇见如图所示的问题了，烦请您指教，非常感谢

**Comment by skyejy** [comment]
![image](https://user-images.githubusercontent.com/26304541/102358108-16a8f200-3fea-11eb-812d-79c8a743b952.png)
您好，感谢您解答上一个问题。 我们又重新安装部署了一遍，deploy目录下运行./start.sh，遇见如图所示的问题了，烦请您指教，非常感谢

**Comment by skyejy** [comment]
> ![image](https://user-images.githubusercontent.com/26304541/102358108-16a8f200-3fea-11eb-812d-79c8a743b952.png)
> 您好，感谢您解答上一个问题。 我们又重新安装部署了一遍，deploy目录下运行./start.sh，遇见如图所示的问题了，烦请您指教，非常感谢

您的这个建议很好 “./start.sh之前可以先运行./stop.sh清理一下环境。” 我们现在已经顺利运行出来了

**Comment by skyejy** [comment]
稍微整理一下我们顺利运行出来的完整步骤，以供参考：
1.参考：https://www.yuque.com/togettoyou/blog/his57f 安装Hyperledger Fabric环境
2.git克隆项目，放在 $GOPATH/src/github.com/togettoyou/blockchain-real-estate 下
3.将go mod环境设置为auto： go env -w GO111MODULE=auto
4.测试chaincode是否正常调用，运行chaincode/blockchain-real-estate/chaincode_test.go测试用例。在含有chaincode_test.go的文件夹chaincode/blockchain-real-estate/下运行"go test"命令行
5.在deploy目录下运行./start.sh,如遇报错，可以先运行./stop.sh，再运行./start.sh
6.在终端执行docker exec cli peer chaincode invoke -C assetschannel -n blockchain-real-estate -c '{"Args":["queryAccountList"]}' c命令，验证链码是否正确安装及区块链网络能否正常工作
7.在含有"sdk_test.go"文件的目录blockchain-real-estate-master/application下执行“go test”
8.运行application，go run main.go
9.打开浏览器访问 http://localhost:8000/web

（最后，再次感谢作者的热心帮助和详细的文档，对初学者太友好了。祝顺利！）
